# Generated by Django 4.2.6 on 2023-11-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_app', '0002_reminder_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
    ]
