# Generated by Django 4.2.6 on 2023-11-13 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_app', '0005_alter_reminder_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Account',
        ),
        migrations.RenameField(
            model_name='reminder',
            old_name='user',
            new_name='account',
        ),
    ]
