# Generated by Django 4.2.6 on 2023-11-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_app', '0007_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='color',
            field=models.CharField(choices=[('Black', 'bg-black text-white'), ('Blue', 'list-group-item-primary'), ('Green', 'list-group-item-success'), ('Red', 'list-group-item-danger'), ('Yellow', 'list-group-item-warning')], default='Black', max_length=100),
        ),
    ]
