# Generated by Django 4.2.6 on 2023-11-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_app', '0009_alter_reminder_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='color',
            field=models.CharField(choices=[('bg-black text-white', 'Black'), ('list-group-item-primary', 'Blue'), ('list-group-item-success', 'Green'), ('list-group-item-danger', 'Red'), ('list-group-item-warning', 'Yellow')], default='bg-black text-white', max_length=100),
        ),
    ]
